services:
  nginx:
    image: nginx:1.21-alpine
    container_name: sos_voice_record_nginx
    volumes:
      - ./sos_voice_record/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/var/www/media
    ports:
      - "8011:80"
    networks:
      - sos_voice_record_network
    depends_on:
      - sos_voice_record

  postgres:
    image: postgres:latest
    container_name: sos_voice_record_postgres
    environment:
      POSTGRES_PASSWORD: pca@1234
      POSTGRES_DB: sos_voice_record
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - sos_voice_record:/var/lib/postgresql/data
    networks:
      - sos_voice_record_network

  sos_voice_record:
    build: ./sos_voice_record/backend
    container_name: sos_voice_record_backend
    stdin_open: true
    tty: true
    ports:
      - "8012:80"
    volumes:
      - ./media:/app/media
      - ./utils:/app/utils
    environment:
      SENDER_NAME: CloudPBX@planetcloud.cloud
      GOOGLE_API_KEY: AIzaSyBBl1ZlKfBfSgb22Agw8oEFSnUWe1V301s
      USER_ID: me
      CITY_DB_NAME: city_backend
      CITY_DB_USER: root
      CITY_DB_PASSWORD: pca@1234
      CITY_DB_HOST: '192.168.100.77'
      CITY_DB_PORT: 3306
      PREFIX_PATH: "https://city.planetcloud.cloud/citybackend/planetcomm/voicerecord/media/sos_voice_record"
      DATABASE_URL: postgresql://root:pca%401234@sos_voice_record_postgres:5432/sos_voice_record
    networks:
      - sos_voice_record_network
    depends_on:
      - postgres

networks:
  sos_voice_record_network:
    driver: bridge

volumes:
  sos_voice_record:
